name: Python CI with pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests and generate reports
        run: |
            mkdir -p reports/failed_tests_screenshots
            pytest --html=reports/report.html --self-contained-html

      - name: Upload test reports and screenshots
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
        if: always()

